#!/bin/bash

PUPPET_SRC=${1}

if [[ -z ${PUPPET_SRC} ]];then
    echo "Need to provide the local puppet src"
    exit 1
fi

ALREADY_RUNNING=$(
    docker ps  | awk '$2 ~ /puppet_master:master/ && $0 ~ /puppetmaster/ {print $1}'
)



if [[ -z ${ALREADY_RUNNING} ]];then
    echo "Can't find running puppetmaster"
    exit 1
fi

./docker-cp ${PUPPET_SRC} ${CONTAINER_ID}:/etc/puppet/environments/default/

echo "restarting puppet-master"
docker exec -it ${CONTAINER_ID} supervisorctl restart unicorn
