#!/bin/bash

PUPPET_SRC=${1}

if [[ -z ${PUPPET_SRC} ]];then
    echo "Need to provide the local puppet src"
    exit 1
fi

ALREADY_RUNNING=$(
    docker ps  | awk '$2 ~ /puppet_master:master/ && $0 ~ /puppetmaster/ {print $1}'
)



if [[ -z ${ALREADY_RUNNING} ]];then
    echo "Can't find running puppetmaster"
    exit 1
fi

CONTAINER_ID=$(docker inspect -f '{{.Id}}' ${ALREADY_RUNNING})

echo "puppetmaster is running as..."
echo "${CONTAINER_ID}"

ROOT_FS="/var/lib/docker/aufs/mnt/${CONTAINER_ID}"
PUPPETMASTER_DIR="${ROOT_FS}/etc/puppet/environments/default/"

echo "sending ${PUPPET_SRC} to puppet master"
sudo rsync -avz --progress  --exclude '.git' ${PUPPET_SRC}/ ${PUPPETMASTER_DIR} >/dev/null

echo "restarting puppet-master"
docker exec -it ${CONTAINER_ID} supervisorctl restart unicorn
