#!/bin/bash

ALREADY_RUNNING=$(docker ps | awk '$2 ~ /puppetmaster/ {print $1}')

if [[ -z ${ALREADY_RUNNING} ]];then

    docker build -t puppetmaster .
    # Start the container
    CONTAINER_ID=$(docker run -P -h puppet -d puppetmaster)
else
    CONTAINER_ID=${ALREADY_RUNNING}
fi


# Grab all the ports
PUPPET_PUPPETDBPORT=$(docker port $CONTAINER_ID 8080 | cut -d: -f2)
PUPPET_PUPPETDBSPORT=$(docker port $CONTAINER_ID 8081 | cut -d: -f2)
PUPPET_PUPPETBOARDPORT=$(docker port $CONTAINER_ID 9090 | cut -d: -f2)

# Show the user the ports
echo "puppetdb (http)"
echo "# http://localhost:$PUPPET_PUPPETDBPORT/"
echo "puppetdb (https)"
echo "# https://localhost:$PUPPET_PUPPETDBSPORT/"
echo "puppet-board (http)"
echo "# http://localhost:$PUPPET_PUPPETBOARDPORT/"

docker exec -it $CONTAINER_ID bash
