#!/bin/bash

ALREADY_RUNNING=$(
    docker ps  | awk '$2 ~ /puppet_master:master/ && $0 ~ /puppetmaster/ {print $1}'
)

if [[ -z ${ALREADY_RUNNING} ]];then

    docker rm puppetmaster
    docker build -t puppet_master:master .
    # Start the container
    CONTAINER_ID=$(docker run -P --name puppetmaster -h puppet -d puppet_master:master)
else
    CONTAINER_ID=${ALREADY_RUNNING}
fi


echo "puppetmaster is running as $CONTAINER_ID"


# Grab all the ports
PUPPET_PUPPETDBPORT=$(docker port $CONTAINER_ID 8080 | cut -d: -f2)
PUPPET_PUPPETDBSPORT=$(docker port $CONTAINER_ID 8081 | cut -d: -f2)
PUPPET_PUPPETBOARDPORT=$(docker port $CONTAINER_ID 9090 | cut -d: -f2)

# Show the user the ports
echo "puppetdb (http)"
echo "# http://localhost:$PUPPET_PUPPETDBPORT/"
echo "puppetdb (https)"
echo "# https://localhost:$PUPPET_PUPPETDBSPORT/"
echo "puppet-board (http)"
echo "# http://localhost:$PUPPET_PUPPETBOARDPORT/"

docker exec -it $CONTAINER_ID bash
